### ISSUE TITLE
Can you to prepare parameter in initional *.ps script for sending UI type.

### ISSUE THREAD

**Issue by P9avel** [antosubash/AbpMicroservice#22]
Hi. i am want to use your script, but i need Blazor WebAssembly for UI. Possible can you to create addition comand line parameter?

**Comment by antosubash** [comment]
PowerShell is created to speed up manual things. If you want a Blazor app create a blazor abp app and copy the files over.  that is what I'm doing with PowerShell.

**Comment by antosubash** [comment]
@thanhtai9606 what help do you need. It seems like you converted everything and I ran your script and it created everything. only `mv` command failed. but I think you can do that manually or add `-rf` so that it will force the move.

**Comment by thanhtai9606** [comment]
Thank you so much. I will try it again

**Comment by antosubash** [comment]
create the dotnet template to create new app.
