### ISSUE TITLE
Blazor Version

### ISSUE THREAD

**Issue by mhkhub** [antosubash/AbpMicroservice#25]

**Comment by mhkhub** [comment]
1) Any plans to have Blazor Version?

**Comment by mhkhub** [comment]
2) There are 7 parts (https://www.youtube.com/watch?v=ICd7dpaCrDo
as of now, 8th is comming in?

**Comment by antosubash** [comment]
here is playlist https://www.youtube.com/watch?v=e95p53tDPis&list=PL-rVxoM6JeHnaHsPJffa54WiDyU4Ue1GS 

I have done upto Part 10.

**Comment by mhkhub** [comment]
Great, Thank you so much, will have a look.

is this 10th the last one, will there be 11th in future?

any plans on blazor or Serverless ?

**Comment by antosubash** [comment]
@mhkhub I will do one more to show how to add a new service. and that will be the last one.

**Comment by mhkhub** [comment]
>  I will do one more to show how to add a new service. and that will be the last one.

Great,Thanks.

planning to follow this approach, in one of the demo, would be more than happy if a video is provided to show 
1) how to add UI for each layer 
2) blazor without blazorise

**Comment by mhkhub** [comment]
waiting for your new article on how to add a new service

**Comment by antosubash** [comment]
@mhkhub  Just add a blog post here https://blog.antosubash.com/posts/netcore-microservice-with-abp-add-new-service-part-11 will make the video soon.

**Comment by antosubash** [comment]
Blazor wasm is added to the project now.
