### ISSUE TITLE
Cannot Run Tasky.DbMigrator

### ISSUE THREAD

**Issue by P9avel** [antosubash/AbpMicroservice#30]
Hi, please look image

**Comment by antosubash** [comment]
@P9avel migration is running successfully. error is coming from rabbitmq and redis. there is no rabbitmq and redis config in the appsettings of dbmigrator. if you are in part 6. ignore this and move along to the next part.

**Comment by P9avel** [comment]
I am get sources from repository.  i am run command 'tye run', but cannot loggining by admin@abp.io  1q2w3E*

**Comment by P9avel** [comment]
![image](https://user-images.githubusercontent.com/95086762/174740440-aa3ceb1e-b2e4-4225-9ffd-cae12d4cc76f.png)

**Comment by antosubash** [comment]
@P9avel I just tried it seems to work. check the logs.

**Comment by P9avel** [comment]
Can you to prepare docker compose file with DBMS, RabbitMQ and Redis. I am want open solution in VS and run whole application by button press. Many thinx for your work and articles

**Comment by antosubash** [comment]
@P9avel my docker stack is here https://github.com/antosubash/docker_stack

**Comment by P9avel** [comment]
I am dont undestand what i did wrong. can you to see my video?

https://user-images.githubusercontent.com/95086762/175116689-e39f4dbe-0b90-4c7f-99d3-7f19811829c4.mp4

**Comment by P9avel** [comment]
Issue was in empty AbpUser table. Because when creating new User in Rabbit sending events. But in   Tasky.DbMigrator in appsettings.json not exists settings. Please add values in appsettings.json

 "RabbitMQ": {
    "Connections": {
      "Default": {
        "HostName": "localhost"
      }
    },
    "EventBus": {
      "ClientName": "Tasky_DbMigrator",
      "ExchangeName": "Tasky"
    }
  },
  "Redis": {
    "Configuration": "127.0.0.1"
  }
